#Importing Libearies


In [1]:
import numpy as np
import pandas as pd

#Loading the data

In [2]:
dataset=pd.read_csv('/content/WineQT.csv')

#Checking for null values

In [3]:
dataset.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

#Finding correlation


In [4]:
def corr_features(corr_df,threshold):
  arr=corr_df.to_numpy()
  feat=set()
  for i in range(len(arr)):
    for j in range(len(arr)):
      if(j>i):
        if(arr[i,j]>=threshold or arr[i,j]<=-threshold):
         feat.add(corr_df.columns[j])
  return feat

In [5]:
corr_df=dataset.corr(method="spearman")
feat=corr_features(corr_df,0.60)
print(feat)

{'pH', 'density', 'citric acid', 'total sulfur dioxide'}


#Dropping correlated values

In [6]:
dataset=dataset.drop('total sulfur dioxide',axis=1)
dataset=dataset.drop('pH',axis=1)
dataset=dataset.drop('citric acid',axis=1)
dataset=dataset.drop('density',axis=1)
dataset.shape

(1143, 9)

In [7]:
dataset.shape

(1143, 9)

#Classifying the quality of wine in good(1) or bad(0)

In [8]:

dataset['quality2'] = [1 if x >= 5 else 0 for x in dataset['quality']]
dataset=dataset.drop('quality',axis=1)


#Dropping unnecssary features

In [9]:
dataset.drop('Id',axis=1)

fixed acidity  volatile acidity  ...  alcohol  quality2
0               7.4             0.700  ...      9.4         1
1               7.8             0.880  ...      9.8         1
2               7.8             0.760  ...      9.8         1
3              11.2             0.280  ...      9.8         1
4               7.4             0.700  ...      9.4         1
...             ...               ...  ...      ...       ...
1138            6.3             0.510  ...     11.0         1
1139            6.8             0.620  ...      9.5         1
1140            6.2             0.600  ...     10.5         1
1141            5.9             0.550  ...     11.2         1
1142            5.9             0.645  ...     10.2         1

[1143 rows x 8 columns]

In [10]:
dataset.head()

fixed acidity  volatile acidity  residual sugar  ...  alcohol  Id  quality2
0            7.4              0.70             1.9  ...      9.4   0         1
1            7.8              0.88             2.6  ...      9.8   1         1
2            7.8              0.76             2.3  ...      9.8   2         1
3           11.2              0.28             1.9  ...      9.8   3         1
4            7.4              0.70             1.9  ...      9.4   4         1

[5 rows x 9 columns]

#Splitting data according to dependent and independent featurex

In [11]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
m,n=X.shape


#Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [13]:
print(X_train)

[[6.900e+00 4.400e-01 1.400e+00 ... 5.800e-01 1.140e+01 1.045e+03]
 [9.500e+00 5.500e-01 2.300e+00 ... 6.700e-01 9.600e+00 7.300e+02]
 [6.500e+00 5.300e-01 2.000e+00 ... 8.300e-01 1.030e+01 1.517e+03]
 ...
 [9.800e+00 3.900e-01 1.650e+00 ... 4.600e-01 1.140e+01 1.181e+03]
 [7.100e+00 5.200e-01 2.600e+00 ... 6.000e-01 9.800e+00 7.790e+02]
 [8.800e+00 3.300e-01 5.900e+00 ... 6.200e-01 1.210e+01 9.740e+02]]


In [14]:
print(y_train)

[1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 1 

In [15]:
print(X_test)

[[9.100e+00 7.750e-01 2.200e+00 ... 5.100e-01 9.600e+00 1.333e+03]
 [6.900e+00 1.090e+00 2.100e+00 ... 4.300e-01 1.140e+01 1.990e+02]
 [9.100e+00 7.600e-01 1.700e+00 ... 1.330e+00 9.100e+00 1.319e+03]
 ...
 [7.400e+00 5.300e-01 1.900e+00 ... 8.600e-01 9.200e+00 8.080e+02]
 [9.200e+00 3.100e-01 2.200e+00 ... 8.600e-01 1.200e+01 1.093e+03]
 [9.600e+00 6.000e-01 2.300e+00 ... 5.700e-01 9.700e+00 6.160e+02]]


In [16]:
print(y_test)

[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


#Training the  model on the Training set

In [17]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 500, criterion = 'entropy', random_state = 0,n_jobs=-1)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=500, n_jobs=-1,
                       random_state=0)

#Saving the model

In [18]:
import joblib
#saving the model to the Disk
file_name='Wine_quality_model'
joblib.dump(classifier,file_name)

['Wine_quality_model']

#Loading the model from disk

In [20]:
import joblib
#loading the model from Disk
loaded_model=joblib.load('/content/Wine_quality_model')

#Predicting the Test set results

In [21]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]

#Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
#confusion matrix
print(cm)
#calculating the accuracy score of the model
print("accuracy")
print((accuracy_score(y_test, y_pred)*100))





[[  0   8]
 [  0 278]]
accuracy
97.2027972027972
